CREATE DATABASE IF NOT EXISTS moderation;
CREATE DATABASE IF NOT EXISTS logger;
CREATE DATABASE IF NOT EXISTS cosmetic;
CREATE DATABASE IF NOT EXISTS ranks;

ALTER USER 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
